from Helpers.motion import Heading

HALF_TURN_COST_FACTOR = 5 * 10  
TURN_COST_FACTOR = 6 
REVERSE_COST_FACTOR = 3 
CLOSE_OBSTACLE_COST = 50  
SAFETY_COST = 1000 
CAPTURE_COST = 100 

MID_TURN_PADDING_DISTANCE = 1
TURN_PADDING_DISTANCE = 2

TURN_RADIUS = 1
HALF_TURN_RADIUS = [2 * TURN_RADIUS, 1 * TURN_RADIUS]
FULL_TURN_RADIUS = [4 * TURN_RADIUS, 2 * TURN_RADIUS]

MOVE_DIRECTIONS = [
    (1, 0, Heading.EAST),
    (-1, 0, Heading.WEST),
    (0, 1, Heading.NORTH),
    (0, -1, Heading.SOUTH),
]

MAX_ITERATIONS = 2000 

EXPANDED_CELL_SIZE = 1
